### ISSUE TITLE
How to run the tests?

### ISSUE THREAD

**Issue by joecritch** [PKuebler/metalsmith-twig#3]
I've noticed that your test has a Jasmine-like `describe` `it` dependency. Along with a `make test` command listed in the `package.json`.

How should the tests be run? Are there some global prerequisites?

**Comment by PKuebler** [comment]
the tests run with mocha. travis like it :)

http://mochajs.org/

**Comment by PKuebler** [comment]
Must "make" are replaced by "mocha"?
