### ISSUE TITLE
TwigException: Cannot extend an inline template.

### ISSUE THREAD

**Issue by genexp** [PKuebler/metalsmith-twig#6]
Hey dudes - I keep getting this error when I use this with the replacement for the metalsmith-templates module, specifically, the new metalsmith-in-place and metalsmith-layouts modules.  Not sure what's happening.

I thought maybe this was the fix:
    https://github.com/genexp/metalsmith-twig/blob/master/lib/index.js#L46

But alas, no.

**Comment by genexp** [comment]
hey @joecritch have you guys run into this? (Seems like you like this one)

**Comment by EvanLovely** [comment]
Seems to be related to justjohn/twig.js#262
